import { Link, useLocation } from "react-router-dom";
import heroImage from "../assets/Image Jun 18, 2026, 09_52_57 PM.png";
import "../styles/Home.css";

const featured = [["Erasmus Mundus Joint Masters", "🌍 Europe", "Master's", "Study a Master's degree at leading European universities."], ["Commonwealth Scholarship", "🇬🇧 UK", "Master's / PhD", "Study in the United Kingdom with financial support."], ["Fulbright Scholarship", "🇺🇸 USA", "Master's", "An opportunity for international graduate students."]];
export default function Home() {
  useLocation(); const currentUser = JSON.parse(localStorage.getItem("currentUser") || "null");
  return <main><section className="hero"><div className="hero-content"><p className="eyebrow">YOUR FUTURE STARTS HERE</p><h1>Find scholarships that <span>match your dreams.</span></h1><p className="hero-text">Discover trusted scholarship opportunities for undergraduate, Master&apos;s, and PhD study—all in one place.</p><div className="hero-buttons"><Link to="/scholarships" className="primary-button">Explore Scholarships</Link>{!currentUser && <Link to="/register" className="secondary-button">Create Free Account</Link>}</div><div className="hero-stats"><div><strong>100+</strong><span>Opportunities</span></div><div><strong>20+</strong><span>Countries</span></div><div><strong>Free</strong><span>For Students</span></div></div></div><div className="hero-image-box"><img src={heroImage} alt="Student" /><div className="floating-card"><span className="card-icon">🎓</span><div><strong>Study Abroad</strong><p>Start your journey today</p></div></div></div></section><section className="categories"><div className="section-heading"><p className="eyebrow">BROWSE BY CATEGORY</p><h2>Find the right opportunity</h2><p>Choose a category and explore scholarships made for you.</p></div><div className="category-grid">{[["💰", "Fully Funded", "Scholarships that cover tuition and living costs."], ["🎓", "Undergraduate", "Funding options for Bachelor's degree students."], ["📚", "Master's & PhD", "Advance your education with global opportunities."], ["📅", "Deadline Soon", "Do not miss scholarships closing soon."]].map(([icon, title, text]) => <Link key={title} to="/scholarships" className="category-card"><span>{icon}</span><h3>{title}</h3><p>{text}</p></Link>)}</div></section><section className="featured"><div className="featured-top"><div><p className="eyebrow">POPULAR OPPORTUNITIES</p><h2>Featured scholarships</h2></div><Link to="/scholarships" className="view-all">View all scholarships →</Link></div><div className="featured-grid">{featured.map(([name, place, level, text]) => <article className="scholarship-card" key={name}><div className="card-top"><span className="badge">Fully Funded</span><span>{place}</span></div><h3>{name}</h3><p>{text}</p><div className="card-footer"><span>{level}</span><Link to="/scholarships">Details →</Link></div></article>)}</div></section>{!currentUser && <section className="cta-section"><div><p className="eyebrow">READY TO BEGIN?</p><h2>Your next scholarship could be one click away.</h2><p>Create a free ScholarPath account and save opportunities you love.</p></div><Link to="/register" className="light-button">Create Account</Link></section>}</main>;
}
