import { Link } from "react-router-dom";
import { useState } from "react";
import "../styles/appPages.css";
const getUser = () => JSON.parse(localStorage.getItem("currentUser") || "null");
export default function Profile() {
  const [user, setUser] = useState(getUser); const [editing, setEditing] = useState(false);
  if (!user) return <main className="content-page empty-page"><h1>You are not logged in.</h1><p>Create an account or log in to view your profile.</p><Link className="primary-button" to="/login">Log in</Link></main>;
  const key = `savedScholarships_${user.id}`; const [saved, setSaved] = useState(() => JSON.parse(localStorage.getItem(key) || "[]"));
  function save(e) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const updated = { ...user, ...data }; localStorage.setItem("currentUser", JSON.stringify(updated)); const users = JSON.parse(localStorage.getItem("scholarPathUsers") || "[]").map((item) => item.id === updated.id ? updated : item); localStorage.setItem("scholarPathUsers", JSON.stringify(users)); setUser(updated); setEditing(false); }
  function remove(index) { const next = saved.filter((_, i) => i !== index); localStorage.setItem(key, JSON.stringify(next)); setSaved(next); }
  const initials = user.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <main className="content-page profile-page"><section className="profile-card-react"><div className="profile-cover" /><div className="profile-body"><div className="profile-heading"><span className="avatar">{initials}</span><button className="secondary-button" onClick={() => setEditing(true)}>Edit profile</button></div><h1>{user.fullName}</h1><p>{user.email}</p><div className="stats"><div><strong>{saved.length}</strong><span>Saved scholarships</span></div><div><strong>{user.aspirant}</strong><span>Study level</span></div><div><strong>Active</strong><span>Account status</span></div></div><div className="info-grid-react">{[["Institution", user.institution], ["Phone number", user.phone], ["Address", user.address], ["Email address", user.email]].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></div></section><section className="saved-section"><div className="section-row"><h2>Saved scholarships</h2><Link to="/scholarships">Find more →</Link></div>{saved.length ? <div className="saved-list">{saved.map((item, index) => <article key={`${item.name || item.title}-${index}`}><div><h3>{item.name || item.title}</h3><p>📍 {item.location || "Location not specified"}</p></div><div><Link to={`/scholarships/${item.id || 1}`}>View</Link><button onClick={() => remove(index)}>Remove</button></div></article>)}</div> : <p className="empty-message">You have not saved any scholarships yet.</p>}</section>{editing && <div className="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-profile-title"><div className="edit-modal-panel"><div className="modal-heading"><div><p className="eyebrow">YOUR PROFILE</p><h2 id="edit-profile-title">Edit profile</h2></div><button type="button" className="modal-close" aria-label="Close profile editor" onClick={() => setEditing(false)}>×</button></div><form className="edit-profile-form" onSubmit={save}><div className="two-columns"><label>Full name<input name="fullName" defaultValue={user.fullName} required /></label><label>Phone number<input name="phone" defaultValue={user.phone} required /></label><label>Institution<input name="institution" defaultValue={user.institution} required /></label><label>Study level<select name="aspirant" defaultValue={user.aspirant}><option>Undergraduate</option><option>Master&apos;s</option><option>PhD</option></select></label></div><label>Address<input name="address" defaultValue={user.address} required /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditing(false)}>Cancel</button><button className="primary-button">Save changes</button></div></form></div></div>}</main>;
}
