import { Link, useParams } from "react-router-dom";
import { scholarships } from "../data/scholarships";
import "../styles/scholarshipDetails.css";

const DetailList = ({ title, items }) => <section className="detail-section"><h2>{title}</h2><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>;
export default function ScholarshipDetails() {
  const { id } = useParams(); const scholarship = scholarships.find((item) => item.id === Number(id));
  if (!scholarship) return <main className="not-found"><h1>Scholarship not found</h1><Link to="/scholarships">Back to scholarships</Link></main>;
  return <main className="scholarship-details"><section className="details-hero"><img src={scholarship.image} alt="" /><div className="details-hero-overlay" /></section><article className="details-container"><Link className="back-link" to="/scholarships">← All scholarships</Link><div className="details-title"><div><span className="funding-badge">{scholarship.funding}</span><h1>{scholarship.name}</h1><p>{scholarship.university}</p></div><a className="apply-btn" href={scholarship.officialWebsite} target="_blank" rel="noreferrer">Visit official website ↗</a></div><div className="details-info"><div><small>LOCATION</small><strong>📍 {scholarship.location}</strong></div><div><small>STUDY LEVEL</small><strong>🎓 {scholarship.available_program}</strong></div><div><small>APPLICATION DEADLINE</small><strong>📅 {scholarship.deadline}</strong></div><div><small>FUNDING</small><strong>💰 {scholarship.funding}</strong></div></div><section className="detail-section intro"><h2>About this scholarship</h2><p>{scholarship.description}</p></section><div className="details-grid"><DetailList title="What this scholarship covers" items={scholarship.benefits} /><DetailList title="Who can apply" items={scholarship.eligibility} /></div><DetailList title="Documents to prepare" items={scholarship.documents} /><section className="application-callout"><div><p className="eyebrow">READY TO APPLY?</p><h2>Confirm the latest requirements before you submit.</h2><p>Official scholarship websites always have the most current instructions and deadlines.</p></div><a className="apply-btn light" href={scholarship.officialWebsite} target="_blank" rel="noreferrer">Open application site ↗</a></section></article></main>;
}
